### DISCUSSION TITLE
What should be the https port?

### DISCUSSION THREAD

**Discussion by uday1kiran** [nginx/docker-nginx-unprivileged#140] [Q&A] [answered]
For http port, we need to change from 80 to 8080.
What should be the value of https?

```
   ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 443
              protocol: TCP
```
